### ISSUE TITLE
How can I do that ? ? (AES)

### ISSUE THREAD

**Issue by lavara123** [tjcampanella/better_cryptography#1]
This is the working Python Code
```python
from pyaes import openssl_aes

sources = '''U2FsdGVkX1/rIYxYVhS1xS+T55ZbD7FErs4XNP6KE3YdHgm1pQuH8kyq4SDTFAfg3R0EFqpiXbCGUusnlgBvClgxmGQHv9hJ5io/O5VBJuKhwPEC4DrjXOwH7iJ/hz4YFHeFpnWnZyLSk44OU8ZdN18FIoLLzMD0UvJ+8hFXDYAxzBT4Hu197IUGgRbH7IWNVnttgN4ltvNGqHHJwQ/ZvuC4TG4PuFUN4XDXNiDaZuqv8g+FcNHKm0NZBatGRUSJGyKD9b9NDOkraMFZX6R/kuCth5hpvmLKULGdhVKgsAc05fRP2JmT7xO1jp5CnlFT3FYVd1AC6sJrsgp/I0Ie4bbotpl2lzhmHhJBpJLRR72WCSJ/7h3cvagFGyR76kbMy2CLMCKlxEJZyKpNsatjkQJPIBdjOwUY/nAeBOiArFf0TytndcVkC0RWINiezIYye8Scf8w7P/sCwD/kLgYEYLoF8d3guBmcngY/aARdNvLGv23UhcbrbAwIhbZXwbI3BouGAAQrtAX6RKDA8deiDhN0Z2oWNmgJPsiQaTF7VndwVvPuiSaa64/szkQHZpShyJ68x1e4wbdI8kzHiJtnA3fKKuMjw1QgGb+GLzkmyqE='''

key = 'e3d64688a262d3a5c455946c9b6a019d'

OpenSSL_AES = openssl_aes.AESCipher()
try:
    sources = json.loads(OpenSSL_AES.decrypt(sources, key))
    source = sources[0]
except:
    raise print('Decrypt key changed')
```

this is the dart code I started, but something seems wrong

```dart
var encryptedText =
        '''U2FsdGVkX1/rIYxYVhS1xS+T55ZbD7FErs4XNP6KE3YdHgm1pQuH8kyq4SDTFAfg3R0EFqpiXbCGUusnlgBvClgxmGQHv9hJ5io/O5VBJuKhwPEC4DrjXOwH7iJ/hz4YFHeFpnWnZyLSk44OU8ZdN18FIoLLzMD0UvJ+8hFXDYAxzBT4Hu197IUGgRbH7IWNVnttgN4ltvNGqHHJwQ/ZvuC4TG4PuFUN4XDXNiDaZuqv8g+FcNHKm0NZBatGRUSJGyKD9b9NDOkraMFZX6R/kuCth5hpvmLKULGdhVKgsAc05fRP2JmT7xO1jp5CnlFT3FYVd1AC6sJrsgp/I0Ie4bbotpl2lzhmHhJBpJLRR72WCSJ/7h3cvagFGyR76kbMy2CLMCKlxEJZyKpNsatjkQJPIBdjOwUY/nAeBOiArFf0TytndcVkC0RWINiezIYye8Scf8w7P/sCwD/kLgYEYLoF8d3guBmcngY/aARdNvLGv23UhcbrbAwIhbZXwbI3BouGAAQrtAX6RKDA8deiDhN0Z2oWNmgJPsiQaTF7VndwVvPuiSaa64/szkQHZpShyJ68x1e4wbdI8kzHiJtnA3fKKuMjw1QgGb+GLzkmyqE=''';
    var pass = 'e3d64688a262d3a5c455946c9b6a019d';

    var ff = base64.decode(encryptedText).toString();

    try {
      final secretKey = SecretKey(pass.codeUnits);

      final newSecretKeyBytes = await secretKey.extractBytes();

      final algorithm = AesCtr.with128bits(
        macAlgorithm: Hmac.sha256(),
      );
      final clearText = await algorithm.decrypt(
        SecretBox(base64.decode(encryptedText),
            nonce: newSecretKeyBytes, mac: Mac.empty),
        secretKey: secretKey,
      );
      var decryptText = String.fromCharCodes(clearText);

      print(decryptText);
    } catch (e) {
      print('aesDecrypt hata');
      print(e.toString());
    }
```

**Comment by tjcampanella** [comment]
Are you positive the AESCipher from the pyaes package is using the same AES algorithm and amount of bits?

**Comment by lavara123** [comment]
> Are you positive the AESCipher from the pyaes package is using the same AES algorithm and amount of bits?

This

https://github.com/Gujal00/ResolveURL/blob/master/script.module.resolveurl/lib/resolveurl/lib/pyaes/openssl_aes.py

**Comment by tjcampanella** [comment]
It says it defaults to 256 bit encryption but you are using 128bits in dart. Try with 256 bits in dart.

**Comment by lavara123** [comment]
> It says it defaults to 256 bit encryption but you are using 128bits in dart. Try with 256 bits in dart.

I don't understand how to extract the problem IV value? Md5 or something is used, when I compile in python, there are byte codes starting with \x, normal number values ​​in darts

**Comment by tjcampanella** [comment]
Oh yeah I didn't notice that before. Seems like the python package is using a function derive_key_and_iv to obtain the iv. You may need to call that function yourself with the same inputs to get the iv. It doesn't seem like the encrypt or decrypt functions return that value.

**Comment by lavara123** [comment]
> Oh yeah I didn't notice that before. Seems like the python package is using a function derive_key_and_iv to obtain the iv. You may need to call that function yourself with the same inputs to get the iv. It doesn't seem like the encrypt or decrypt functions return that value.

I tried this but it doesn't seem to be complete with Uint8List or I couldn't and I guess the Md5 process is not in this library

**Comment by dmorawetz** [comment]
The following code prints the expected json. Just call `decrypt()`. @tjcampanella was right, you need to use 256 bits and no HMAC. The codes string with `\x` suggest hexadecimal values. You can print them in python with `print(key.hex())`, in dart with `print(hex.encode(key));`.

```dart
import 'package:convert/convert.dart';
import 'package:crypto/crypto.dart';

import 'package:better_cryptography/better_cryptography.dart' as bc;
import 'dart:convert';

Future<void> decrypt() async {
  var encryptedText =
      '''U2FsdGVkX1/rIYxYVhS1xS+T55ZbD7FErs4XNP6KE3YdHgm1pQuH8kyq4SDTFAfg3R0EFqpiXbCGUusnlgBvClgxmGQHv9hJ5io/O5VBJuKhwPEC4DrjXOwH7iJ/hz4YFHeFpnWnZyLSk44OU8ZdN18FIoLLzMD0UvJ+8hFXDYAxzBT4Hu197IUGgRbH7IWNVnttgN4ltvNGqHHJwQ/ZvuC4TG4PuFUN4XDXNiDaZuqv8g+FcNHKm0NZBatGRUSJGyKD9b9NDOkraMFZX6R/kuCth5hpvmLKULGdhVKgsAc05fRP2JmT7xO1jp5CnlFT3FYVd1AC6sJrsgp/I0Ie4bbotpl2lzhmHhJBpJLRR72WCSJ/7h3cvagFGyR76kbMy2CLMCKlxEJZyKpNsatjkQJPIBdjOwUY/nAeBOiArFf0TytndcVkC0RWINiezIYye8Scf8w7P/sCwD/kLgYEYLoF8d3guBmcngY/aARdNvLGv23UhcbrbAwIhbZXwbI3BouGAAQrtAX6RKDA8deiDhN0Z2oWNmgJPsiQaTF7VndwVvPuiSaa64/szkQHZpShyJ68x1e4wbdI8kzHiJtnA3fKKuMjw1QgGb+GLzkmyqE=''';
  var pass = 'e3d64688a262d3a5c455946c9b6a019d';
  final passList = utf8.encode(pass);

  var ff = base64.decode(encryptedText);

  const offset = "Salted__".length;
  final salt = ff.sublist(offset, 16);
  final data = ff.sublist(offset + salt.length);

  final keyAndIv = deriveKeyAndIv(passList, salt);
  print(hex.encode(keyAndIv.key));
  print(hex.encode(keyAndIv.iv));

  try {
    final secretKey = bc.SecretKey(keyAndIv.key);

    final algorithm = bc.AesCbc.with256bits(
      macAlgorithm: bc.MacAlgorithm.empty,
    );
    final clearText = await algorithm.decrypt(
      bc.SecretBox(data, nonce: keyAndIv.iv, mac: bc.Mac.empty),
      secretKey: secretKey,
    );
    var decryptText = String.fromCharCodes(clearText);

    print(decryptText);
  } catch (e) {
    print('aesDecrypt hata');
    print(e.toString());
  }
}

class KeyAndIv {
  final List<int> key;
  final List<int> iv;

  KeyAndIv(this.key, this.iv);
}

KeyAndIv deriveKeyAndIv(List<int> password, List<int> salt,
    [int keyLength = 32, int ivLength = 16]) {
  List<int> d = List.empty(growable: true);
  List<int> di = List.empty(growable: true);

  while (d.length < keyLength + ivLength) {
    di = md5.convert(di + password + salt).bytes;
    d += di;
  }
  return KeyAndIv(
    d.sublist(0, keyLength),
    d.sublist(keyLength, keyLength + ivLength),
  );
}
```

Hope this helps.

**Comment by lavara123** [comment]
> The following code prints the expected json. Just call `decrypt()`. @tjcampanella was right, you need to use 256 bits and no HMAC. The codes string with `\x` suggest hexadecimal values. You can print them in python with `print(key.hex())`, in dart with `print(hex.encode(key));`.
> 
> Hope this helps.



thank you so much. I did it with Point Castle that the only class result would be meaningless value at the end

```dart
/// [0] = keyByte [1] = IV
List<Uint8List> deriveKeyAndIV(String passphrase, Uint8List salt,
      [int keyLength = 32, int ivLength = 16]) {
    Uint8List d = Uint8List(0);
    Uint8List di = Uint8List(0);

    final md5 = MD5Digest();

    while (d.length < keyLength + ivLength) {
      di = md5.process(Uint8List.fromList(di + passphrase.codeUnits + salt));
      d = Uint8List.fromList(d + di);
    }

    return [
      d.sublist(0, keyLength),
      d.sublist(keyLength, keyLength + ivLength)
    ];
  }


String opensslAesCbcDecrypt(String pass, String encryptedText) {
    var message = base64.decode(encryptedText);
    var salt = message.sublist(8, 16);
    var cipherText = message.sublist(16, message.length);
    var temp = deriveKeyAndIV(pass, salt);

    var key = temp[0];
    var iv = temp[1];

    assert([128, 192, 256].contains(key.length * 8));
    assert(128 == iv.length * 8);

    try {
      final cbc = CBCBlockCipher(AESEngine())
        ..init(false, ParametersWithIV(KeyParameter(key), iv)); // false=decrypt

      // Decrypt the cipherText block-by-block

      final paddedPlainText = Uint8List(cipherText.length); // allocate space

      var offset = 0;
      while (offset < cipherText.length) {
        offset += cbc.processBlock(cipherText, offset, paddedPlainText, offset);
      }
      assert(offset == cipherText.length);

      return String.fromCharCodes(paddedPlainText.sublist(
          0, paddedPlainText.length - paddedPlainText.last));
    } catch (e) {
      print('aesDecrypt hata');
      print(e.toString());
      return '';
    }
  }
```

It deletes the meaningless results coming at the end with this
```dart
return String.fromCharCodes(paddedPlainText.sublist(0, paddedPlainText.length - paddedPlainText.last));
```

Why do characters appear at the end in Point Castle?

**Comment by dmorawetz** [comment]
Since it is a block cipher, the encoding and decoding happens in [blocks of 128 bits](https://security.stackexchange.com/a/6048). The data to encrypt will not always be divisible by 128 bits, and therefore some padding needs to be added at the end of the data. It's meaningless data just to fill up to the needed length. When decrypting, you need to remove this padding, like you do with: 
```dart
return String.fromCharCodes(paddedPlainText.sublist(0, paddedPlainText.length - paddedPlainText.last));
```

This dart library removes the padding automatically. You can see it in the [dart implementation](https://github.com/tjcampanella/better_cryptography/blob/2828ce1e2d671acde02478e9735ac8da04423aa6/better_cryptography/lib/src/dart/aes_cbc.dart#L140).

**Comment by lavara123** [comment]
> Since it is a block cipher, the encoding and decoding happens in [blocks of 128 bits](https://security.stackexchange.com/a/6048). The data to encrypt will not always be divisible by 128 bits, and therefore some padding needs to be added at the end of the data. It's meaningless data just to fill up to the needed length. When decrypting, you need to remove this padding, like you do with:
> 
> ```dart
> return String.fromCharCodes(paddedPlainText.sublist(0, paddedPlainText.length - paddedPlainText.last));
> ```
> 
> This dart library removes the padding automatically. You can see it in the [dart implementation](https://github.com/tjcampanella/better_cryptography/blob/2828ce1e2d671acde02478e9735ac8da04423aa6/better_cryptography/lib/src/dart/aes_cbc.dart#L140).

Thank you so much for your interest and help.👍
